version: '2'
catalog:
  name: "WordPress"
  version: "4.9.5"
  description: "Blog tool, publishing platform and CMS based on bitnami images"
  questions:
    - variable: DOMAIN
      description: "Wordpress Domain"
      label: "Wordpress Domain"
      required: true
      default: "test.de"
      type: "string"
    - variable: mariadb_root_password
      description: "MariaDB root password, set on first run"
      label: "MariaDB Root Password"
      required: true
      default: "mariadb_my_root"
      type: "password"
    - variable: mariadb_user
      description: "MariaDB database user, created on first run"
      label: "MariaDB Database User"
      required: true
      default: "wordpress"
      type: "string"
    - variable: mariadb_user_password
      description: "MariaDB database user password, set on first run"
      label: "MariaDB Database User Password"
      required: true
      default: "wordpress_password"
      type: "password"
    - variable: mariadb_database_name
      description: "WordPress database name"
      label: "WordPress database name"
      required: true
      default: "wordpress"
      type: "string"
    - variable: wordpress_username
      description: "WordPress application username"
      label: "WordPress application username"
      required: true
      default: "admin"
      type: "string"
    - variable: wordpress_password
      description: "WordPress application password"
      label: "WordPress application password"
      required: true
      default: "bitnami"
      type: "password"
    - variable: volume_driver
      description: "Volume driver to use with this service"
      label: "Volume driver"
      required: true
      default: "rancher-nfs"
      type: enum
      options:
        - local
        - rancher-nfs
services:
  wordpress:
    scale: 1
    start_on_create: true
    lb_config:
      port_rules:
      - target_port: 80
        hostname: ${DOMAIN}

  mariadb:
    scale: 1
    start_on_create: true

  redirect-https:
    scale: 1
    start_on_create: true
    lb_config:
      port_rules:
      - target_port: 80
        hostname: ${DOMAIN}
        
  letsencrypt:
    scale: 1
    start_on_create: true
    lb_config:
      port_rules:
      - target_port: 80
        hostname: ${DOMAIN}