version: '2'

catalog:

  name: meshviewer
  version: 1
  description: Meshviewer - a Freifunk Visualisation
  questions:
    - variable: DOMAIN
      default: your-domain.de
      label: Domain
      required: true
      type: string

services:

  meshviewer:
    scale: 1
    start_on_create: true
    lb_config:
      port_rules:
      - target_port: 80
        hostname: ${DOMAIN}

  nginx:
    scale: 1
    start_on_create: true

  letsencrypt:
    scale: 1
    start_on_create: true
    lb_config:
      port_rules:
      - target_port: 80
        hostname: ${DOMAIN}