version: '2'

catalog:

  name: ffrs-website
  version: 2
  description: Freifunk Rhein Sieg Webseite
  questions:
    - variable: DOMAIN
      default: freifunk-rhein-sieg.net
      label: Domain
      required: true
      type: string


services:

  website:
    scale: 1
    start_on_create: true