version: '2'

services:

  cadvisor:
    image: google/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    depends_on:
      - influxdb
    environment:
      INFLUXDB_HOST: localhost
      INFLUXDB_PORT: 8086
      INFLUXDB_NAME: cadvisor
      INFLUXDB_USER: admin
      INFLUXDB_PASS: ${INFLUXDB_PASSWORD}
    command: -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=db:8086
    links:
      - influxdb:db
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.global: 'true'
      io.rancher.scheduler.affinity:host_label: global=yes
    logging:
      driver: syslog

  influxdb:
    image: tutum/influxdb
    volumes:
      - influxdb:/data
    environment:
      PRE_CREATE_DB: cadvisor   
      ADMIN_USER: admin   
      INFLUXDB_INIT_PWD: ${INFLUXDB_PASSWORD}
    labels:
      io.rancher.container.hostname_override: container_name

  grafana:
    image: grafana/grafana
    environment:
      GF_SERVER_ROOT_URL: https://${DOMAIN}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
    volumes:
    - grafana:/var/lib/grafana
    links:
    - influxdb:db
    labels:
      io.rancher.container.pull_image: always
      rap.host: ${DOMAIN}
      rap.le_host: ${DOMAIN}
      rap.port: 3000

volumes:
  grafana:
    driver: local
  influxdb:
    driver: local

